#!/usr/bin/env bash
# Emit this plugin's rules as SessionStart additionalContext.
# (SessionStart does not support prompt-type hooks; command-type + JSON stdout is the supported path.)
cat <<'JSON'
{
  "hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": "[ml-research-toolkit rules, apply to VLM/LLM research work]\n\nTOOL-CALL ENCODING (hard rule): always write Korean and other non-ASCII strings in tool-call parameters as literal UTF-8; never as \\uXXXX unicode escapes. Hand-spelled hex codepoints produce near-miss syllables that silently corrupt Hangul (e.g. 완료 rendered as 완릷); see anthropics/claude-code#83033. Applies to every tool parameter, especially AskUserQuestion labels, task titles, and file contents.\n\nKOREAN PROSE STYLE (anti-slop): no em dash (—): use commas, parentheses, a colon, or split the sentence; also avoid -- and en dash as substitutes. Do not use the middle dot (·) to list keywords: write 'A, B, C' or 'A와 B' instead. Mix 해요체 and 습니다체 rather than repeating one ending; default about 5:5 for blog/guide prose, adjust by context (more 습니다체 for reports and release notes, more 해요체 for tutorials and conversational replies), never drop to 반말/음슴체. Bullets, rule statements, and table cells are exempt; English paper prose is out of scope. Skip filler openers like '~의 핵심은' and '결론적으로 말하면'.\n\nFact & citation integrity: never write a guessed fact or citation as confirmed. Prefer primary sources (arXiv, ACL Anthology, venue proceedings originals, official repos). Verify citations before use, delegating to arxiv-verify or citation-workflow (skills), and prior-art survey to paper-lookup or literature-scout. Mark unverifiable citations as PLACEHOLDER + TODO; never fabricate. State uncertainty; label estimates as estimates. Author and review separation: don't self-approve your own claims, a claim-evidence map or reviewer-angle pass is a separate lane.\n\nCode style: match surrounding code; small focused diffs; type hints on public signatures; fix seeds for reproducibility; be explicit about device and dtype; no hardcoded secrets or absolute local paths; notebooks beginner-friendly, scripts precise.\n\nCommunication: Korean prose, English for technical terms, identifiers, and code. No unsupported superlatives ('always', 'best', 'perfect'); use conditionals instead. Conclusion first. Honest status reporting (failed experiments reported as failed, with evidence).\n\nFull rule text ships in this plugin's rules/ directory (code-style, communication, fact-integrity). See the plugin README to enable them as always-on @import rules in your own CLAUDE.md."
  }
}
JSON
exit 0
